### ISSUE TITLE
PR for ractive 0.9

### ISSUE THREAD

**Issue by krityan** [maxgalbu/gulp-ractive#4]
I have an updated branch for use with Ractive 0.9, however due to your branch scheme I have nowhere to point the PR to.

Would it be possible to get a 0.9 branch to PR to, and get this updated to 0.9 on NPM? We're using this plugin with our project and just migrated to Ractive 0.9, we're using an updated local copy but would rather use an updated one from NPM.

**Comment by maxgalbu** [comment]
Done: https://www.npmjs.com/package/gulp-ractive
